### PR TITLE
Implemented multithreaded scanning

### PR DESCRIPTION
**Pull request by edc71**
Improvement abt 2-2.5 times on uncompressed files.

### CODE REVIEW

**Comment by jwestfall69** [comment]
What kinda of performance gain are you seeing on the multi-threaded hashing code?  hashing should be pretty quick in general.  Your code is creating/destroying 1 to 3 new threads per Buffersize read().  There is overhead when creating/destroying threads which makes me think there is little to no gain in speed by doing this.

**Comment by edc71** [comment]
The performance gain is abt 2 - 2.5 times the original performance, confirmed by another user. I am using slightly bigger buffers (2MB for zipped, 6MB for uncompressed files).

The overhead for creating threads is minimal. I tested this on Win7 against WinXP a long time ago.. WIn7 is able to create at least 100k threads/s on a decent machine (at that time a core i7 9xx series)

Hashing is quite an intensive task, limited to abt 100MB/s on a single thread. sha1, md5 and crc32 dont differ very much.. so multithreading this gives quite an advantage.

On small files the gain isnt that much, but that is limited by IO (seeks)

On uncompressed WII files I noticed abt 3 times speedup (have a fast Raid5 setup)

**Comment by edc71** [comment]
Here is a comment from an everyday user:

My pc is rather sluggish, it's difficult to compare the speed in scanning that I am getting with the speed you are getting.  I scanned (uncompressed) 2.75 GB (30 files) in 44 seconds before (= 62.5 MBs), and the same amount in 19 seconds with your revision "a" changes to the code (= 144.7 MBs).   That's a great speedup, but the "before" rate is so slow, you can tell my system isn't taking full advantage of the optimization.

**Comment by jwestfall69** [comment]
I tried this under linux/mono and it does have a nice speed up.

Using a single 4.2G dvd.iso in ToSort, fully in the disk cache, I got the following results.
RomVault master: 72.4 seconds (58.6 MB/s)
edc71 master: 34.2 seconds (124.1 MB/s)

Some additional number not related to your pull request, but that are interesting:
Individual hash speeds in mono against dvd.iso
crc32: 22.4 seconds (189.5 MB/s)
md5: 17.9 seconds (238.5 MB/s)
sha1: 33.3 seconds (127.5 MB/s)

Individual hash speeds from linux cli utils against dvd.iso
crc32: 4.6 seconds (923.0 MB/s)
md5sum: 7.5 seconds (566.1 MB/s)
sha1sum: 11.5 seconds (369.2 MB/s)

**Comment by edc71** [comment]
40% gain on larger files

**Pull request closed without merging**
